config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games
  resources :game_logs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'games#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  validates :home_team, presence: true
  validates :away_team, presence: true

  def title
    "#{away_team} at #{home_team}"
  end

  def display_date
    date.strftime("%B %-d, %Y")
  end
end

app/models/game_log.rb
class GameLog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_logs_controller.rb
class GameLogsController < ApplicationController
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
    respond_to do |format|
      format.html
      format.json { render json: @games }
    end
  end

  def new
    @game = Game.new
  end

  def show
    @game = Game.find(params[:id])
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to games_path
    else
      render :new
    end
  end

  private

  def game_params
    params.require(:game).permit(:date, :home_team, :away_team, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_logs_helper.rb
module GameLogsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<h1>Games</h1>
<%= link_to 'New Game', new_game_path %>

<table class="table">
  <tr>
    <th>Date</th>
    <th>Home</th>
    <th>Away</th>
    <th>Description</th>
    <th></th>
  </tr>
  <% @games.each do |game| %>
    <tr>
      <td><%= game.date %></td>
      <td><%= game.home_team %></td>
      <td><%= game.away_team %></td>
      <td><%= game.description %></td>
      <td><%= link_to 'Watch Film', game_path(game) %></td>
    </tr>
  <% end %>
</table>

app/views/games/new.html.erb
<h1>New Game</h1>

<div class="row">
  <div class="col-sm-6">
    <%= simple_form_for(@game, html: { class: 'form' }) do |f| %>
      <%= f.input :date %>
      <%= f.input :away_team %>
      <%= f.input :home_team %>
      <%= f.input :description %>
      <%= f.button :submit, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<h1><%= @game.title %></h1>
<p><%= @game.display_date %></p>

<div class="card">
  <div class="card-header">
    <div class="float-md-left">
      <%= link_to 'Start', 'javascript:void(0);', id: 'js-start-recording', class: 'btn btn-success' %>
      <%= link_to 'Stop', 'javascript:void(0);', id: 'js-stop-recording', class: 'btn btn-danger' %>
    </div>
    <div id="js-recording-now" class="float-md-right" style="display: none;">
      <%= image_tag 'icon-mic-red-bg.png', size: "23x38" %>
    </div>
  </div>
  <div class="card-body">
    <h5 class="card-title">Game Log</h5>
    <div id="js-speech-log" class="card-text"></div>
  </div>
</div>

<br>
<%= link_to 'Games', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasketballData</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="notifications" class="container">
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="row">
  <h1>Index</h1>
</div>